/* This file is auto-generated by scripts/fetch-pdf-fonts.mjs */
export const GENERATED_PDF_FONT_CONFIG = {
  "Nunito": {
    "family": "Nunito",
    "fonts": [
      {
        "src": "/fonts/nunito/Nunito[wght].ttf",
        "fontWeight": 400,
        "fontStyle": "normal"
      }
    ]
  },
  "Quicksand": {
    "family": "Quicksand",
    "fonts": [
      {
        "src": "/fonts/quicksand/Quicksand[wght].ttf",
        "fontWeight": 400,
        "fontStyle": "normal"
      }
    ]
  },
  "Poppins": {
    "family": "Poppins",
    "fonts": [
      {
        "src": "/fonts/poppins/Poppins-Bold.ttf",
        "fontWeight": 700,
        "fontStyle": "normal"
      },
      {
        "src": "/fonts/poppins/Poppins-ExtraBold.ttf",
        "fontWeight": 700,
        "fontStyle": "normal"
      },
      {
        "src": "/fonts/poppins/Poppins-Regular.ttf",
        "fontWeight": 400,
        "fontStyle": "normal"
      }
    ]
  },
  "Merriweather": {
    "family": "Merriweather",
    "fonts": [
      {
        "src": "/fonts/merriweather/Merriweather[opsz,wdth,wght].ttf",
        "fontWeight": 400,
        "fontStyle": "normal"
      }
    ]
  },
  "Baloo 2": {
    "family": "Baloo 2",
    "fonts": [
      {
        "src": "/fonts/baloo2/Baloo2[wght].ttf",
        "fontWeight": 400,
        "fontStyle": "normal"
      }
    ]
  },
  "Fredoka": {
    "family": "Fredoka",
    "fonts": [
      {
        "src": "/fonts/fredoka/Fredoka[wdth,wght].ttf",
        "fontWeight": 400,
        "fontStyle": "normal"
      }
    ]
  },
  "Comfortaa": {
    "family": "Comfortaa",
    "fonts": [
      {
        "src": "/fonts/comfortaa/Comfortaa[wght].ttf",
        "fontWeight": 400,
        "fontStyle": "normal"
      }
    ]
  },
  "Pacifico": {
    "family": "Pacifico",
    "fonts": [
      {
        "src": "/fonts/pacifico/Pacifico-Regular.ttf",
        "fontWeight": 400,
        "fontStyle": "normal"
      }
    ]
  },
  "Open Sans": {
    "family": "Open Sans",
    "fonts": [
      {
        "src": "/fonts/opensans/OpenSans[wdth,wght].ttf",
        "fontWeight": 400,
        "fontStyle": "normal"
      }
    ]
  },
  "Lato": {
    "family": "Lato",
    "fonts": [
      {
        "src": "/fonts/lato/Lato-Bold.ttf",
        "fontWeight": 700,
        "fontStyle": "normal"
      },
      {
        "src": "/fonts/lato/Lato-ExtraBold.ttf",
        "fontWeight": 700,
        "fontStyle": "normal"
      },
      {
        "src": "/fonts/lato/Lato-Regular.ttf",
        "fontWeight": 400,
        "fontStyle": "normal"
      }
    ]
  },
  "Inter": {
    "family": "Inter",
    "fonts": [
      {
        "src": "/fonts/inter/Inter[opsz,wght].ttf",
        "fontWeight": 400,
        "fontStyle": "normal"
      }
    ]
  },
  "Rubik": {
    "family": "Rubik",
    "fonts": [
      {
        "src": "/fonts/rubik/Rubik[wght].ttf",
        "fontWeight": 400,
        "fontStyle": "normal"
      }
    ]
  },
  "Roboto": {
    "family": "Roboto",
    "fonts": [
      {
        "src": "/fonts/roboto/Roboto[wdth,wght].ttf",
        "fontWeight": 400,
        "fontStyle": "normal"
      }
    ]
  },
  "Nunito Sans": {
    "family": "Nunito Sans",
    "fonts": [
      {
        "src": "/fonts/nunitosans/NunitoSans[YTLC,opsz,wdth,wght].ttf",
        "fontWeight": 400,
        "fontStyle": "normal"
      }
    ]
  },
  "Work Sans": {
    "family": "Work Sans",
    "fonts": [
      {
        "src": "/fonts/worksans/WorkSans[wght].ttf",
        "fontWeight": 400,
        "fontStyle": "normal"
      }
    ]
  },
  "Fredoka One": {
    "family": "Fredoka",
    "fonts": [
      {
        "src": "/fonts/fredoka/Fredoka[wdth,wght].ttf",
        "fontWeight": 400,
        "fontStyle": "normal"
      }
    ]
  }
} as const;
